### ISSUE TITLE
Set up Android swaglines

### ISSUE THREAD

**Issue by sindrenm** [hyperoslo/playbook#24]

**Comment by NSElvis** [comment]
Might be better if it has it's own repo

https://github.com/hyperoslo/iOS-playbook

**Comment by sindrenm** [comment]
Well, I'd want to put it under hyperoslo/android-playbook in that case. But I see your point, @NSElvis!

**Comment by timkurvers** [comment]
Heh! :smile:

**Comment by NSElvis** [comment]
@sindrenm Classic Sindre :)

**Comment by sindrenm** [comment]
You've also got this one, though: https://github.com/hyperoslo/playbook/tree/master/iOS.

**Comment by jgorset** [comment]
Yeah not sure what the deal with that is, actually, @NSElvis and @zenangst. I was just looking in hyperoslo/ios-playbook for something and it turned out it was in hyperoslo/playbook. What goes where?

**Comment by NSElvis** [comment]
@jgorset You are (goddamn) right, we might want to move this to `ios-playbook` and maybe also have a ruby one.

**Comment by jgorset** [comment]
Yeah, I think either organize everything under the iOS directory in `playbook` or move it here and do the same thing for Ruby and Android?

**Comment by NSElvis** [comment]
@jgorset I like that we separate platforms into different repos and use this for general things. Then it's easier to subscribe for notifications and make issues.

**Comment by jgorset** [comment]
Good argument. :+1:

**Comment by NSElvis** [comment]
@sindrenm @jgorset done! 

https://github.com/hyperoslo/iOS-playbook

**Comment by sindrenm** [comment]
:+1:

**Comment by NSElvis** [comment]
Fixed by https://github.com/hyperoslo/android-playbook
