### ISSUE TITLE
How to get a bank account?

### ISSUE THREAD

**Issue by jgorset** [hyperoslo/playbook#36]
We should document how to set up an account with a Norwegian Bank in the playbook.

**Comment by richardoti** [comment]
I would appreciate. I think, tomorrow I will go to the Nordea bank and then, to some other, so I could tell the 1st person experience.

**Comment by sindrenm** [comment]
Does this have anything to do with Hyper, though? :stuck_out_tongue:

**Comment by sindrenm** [comment]
I mean, we could document how to build houses out of bricks and wood as well, but is that really necessary?

**Comment by jgorset** [comment]
Haha, I guess, @sindrenm, but this is pretty relevant to hiring people from abroad. I think it goes well with the other stuff [here](https://github.com/hyperoslo/playbook/blob/master/YOU_GOT_HIRED.md#how-do-i-get-there).

**Comment by jgorset** [comment]
:+1: @richardoti

**Comment by 3lvis** [comment]
@richardoti DNB is the best, don't go to Nordea

**Comment by timkurvers** [comment]
I have Nordea personally, it's pretty alright :smile:

**Comment by richardoti** [comment]
I need to go to Nordea only because I already have the EURO account there. Maybe I would be able to put my money on the account.

**Comment by sindrenm** [comment]
yA Bank!

**Comment by jgorset** [comment]
Hi old friends! I'm cleaning up my issues, so I'm closing this one. Trust you won't mind. :blush:
