### ISSUE TITLE
Have a list of apartments ready for when people get here

### ISSUE THREAD

**Issue by jgorset** [hyperoslo/playbook#40]
We should put out an ad on finn.no to announce that we're in the business for renting an apartment near the office and compile a list of options to go through with new hires when they arrive. And then we should join them for the viewings!

**Comment by RamonGilabert** [comment]
I'd add here the explanation on how to rent an apartment, the thing that you need a bank account and stuff like that, but Hyper is going to help you any way with it!

**Comment by jgorset** [comment]
Great!

**Comment by jgorset** [comment]
I wrote about finding an apartment in #41.

**Comment by RamonGilabert** [comment]
How would you do that though? Sending the person the email with the list of apartments, or keep a list of apartments to rent here in github? While the second one is a mess in my opinion, we could do the first, then this become a non issue, right?

**Comment by jgorset** [comment]
I must have missed your reply on this one, @RamonGilabert! I thought we'd through the list with the new team member once they get here – we'd have a full month to visit their top choices and decide. What do you think?

**Comment by RamonGilabert** [comment]
Right, so you'd pay the first month of an AirBnB and then keep sending him apartments right?

**Comment by jgorset** [comment]
Yep!

**Comment by jgorset** [comment]
Hi old friends! I'm cleaning up my issues, so I'm closing this one. Trust you won't mind. :blush:
