### ISSUE TITLE
Decision-making / documentation

### ISSUE THREAD

**Issue by timkurvers** [hyperoslo/playbook#49]
With [working remotely](https://github.com/hyperoslo/playbook/issues/47) just around the corner, it's time to take a stab at improving decision-making and documentation.

Topics to discuss:
- Initial project documentation / structure.
- Document decisions / odd solutions every step of the way.
- Limit brief decisive discussions between individual team members and/or inform others through documentation.
- Tooling.

**Comment by fespinoza** [comment]
regarding documentation, i think there are some important points to consider:

- **what kind of thing are we documenting**: how a particular feature works, maybe a cross cutting concern (for example, how authentication works in an API)
- **self contained**: like a github issue, more than slack channel, try to see the full conversation of a single topic in one place (and not mixing it up with other topics)
- **quickly see that a _Document_ is about and what is the current behavior and why**: (what, how and why), it's important to be able to see all the conversation and changes regarding a topic, but over all of that, you want to highlight the current state of things and why that current state is what it is.
- **people know where to look for information**: it should be fast to locate the topic or the detail you want to know about.

on the other hand, this should be live, and collaborative, hopefully close integration to github, code and project planning

about tooling, the best things i can think of is Github (+ issues/PR) and basecamp
