### ISSUE TITLE
Improving streaming quality for live events and big meetings

### ISSUE THREAD

**Issue by ohenrik** [hyperoslo/playbook#50]
To improve the quality of streaming live events i propose using a combination of Herocast (go pro cameras), a sound mixer, video mixer (might be enough with software for the Herocast system) and some good quality speaker microphones.

Video:
http://gopro.com/herocast

Sound:
http://en-us.sennheiser.com/wireless-d1-lavalier-microphone-system-live-stage-evolution-ew-d1-me-2
http://www.danmusikk.no/product/behringer-xenyx-x1204-usb-mikser-4464/

**Comment by sindrenm** [comment]
Okay, then. :stuck_out_tongue:

**Comment by timkurvers** [comment]
Heh! :+1:

**Comment by ohenrik** [comment]
It was outdated, We still need to improve the sound quality but we should do it in another way. Don't have time to write a good proposal yet. so i just closed this one for now :)

**Comment by jgorset** [comment]
:grinning:
