### ISSUE TITLE
File names for JavaScript and CSS

### ISSUE THREAD

**Issue by jgorset** [hyperoslo/playbook#65]
Okay, let's put it to a vote:

👍 means you prefer `underscore_case.js|css`.
👎 means you prefer `dash-case.js|css`.

Please feel free to add a comment with your reflections, or to add another option to the list (I'll edit the post accordingly). What do you think, @hyperoslo/web?

**Comment by enderahmetyurt** [comment]
Can we vote? 🙈

**Comment by RamonGilabert** [comment]
Do it, @enderahmetyurt!

**Comment by jgorset** [comment]
Hi @enderahmetyurt! 😁

**Comment by jgorset** [comment]
Well, that's about as unanimous as it gets! `dash-case.css|js` it is!

**Comment by sindrenm** [comment]
This is specifically for web projects, right?

**Comment by jgorset** [comment]
It's JavaScript and CSS, so yes.

**Comment by sindrenm** [comment]
And HTML, I suppose.

**Comment by sindrenm** [comment]
(I actually didn't notice the title had JavaScript and CSS in them. My bad. :stuck_out_tongue:)
